### ISSUE TITLE
Duplicate repository with plpgsql?

### ISSUE THREAD

**Issue by GeertJohan** [sqids/sqids-postgresql#1]
Maybe it's not a duplicate, but then it would be interesting to explain the difference to PLpgSQL.

Perhaps this repo aims to build a Postgres `EXTENSION`, wheras PLpgSQL can be imported by a postgres as a `FUNCTION` (using a non-superuser role / at runtime)?

**Comment by 4kimov** [comment]
Good question. The reason there's two is because of older Hashids projects:

1. https://github.com/array-analytics/plpg_hashids/blob/master/src/all_hashids.sql
2. https://github.com/iCyberon/pg_hashids/blob/master/hashids.c

Not sure if anyone will take on porting Sqids the same way, but it's important that those two pages on the website link to the original implementation so it can be found easily.
